project:
  type: book
  output-dir: "../../_site/books/epistles"
book:
  title: "Epistles"
  description: "Essays, Communiqu√©s and Supplications on Various Topics"
  author: "Stephen Huntley"
  site-url: "https://stephen.huntley.link/books/epistles"
  cover-image: "img/epistles-cover.png"
  date: "4/21/2023"
  favicon: "img/letter-quill.png"
  repo-subdir: "books/epistles"
  navbar:
    title: "Epistles"
  chapters:
    - index.qmd
    - chapters/1_what_news.qmd
    - chapters/2_system.qmd
    - chapters/3_about.qmd
bibliography: Epistles.bib
format:
  html:
    theme: cosmo
    css: bookstyles.css
    number-sections: false
    embed-resources: false
  pdf:
    number-sections: false
metadata-files:
  - "../_books.yml"
